#!/usr/bin/env bash
set -euo pipefail

DOMAIN_NAME="${DOMAIN_NAME:-}"
CERTBOT_EMAIL="${CERTBOT_EMAIL:-}"
CERTBOT_DOMAINS="${CERTBOT_DOMAINS:-}"
CERTBOT_STAGING="${CERTBOT_STAGING:-0}"
CERTBOT_RENEW_INTERVAL_SECONDS="${CERTBOT_RENEW_INTERVAL_SECONDS:-43200}"
CLOUDFLARE_API_TOKEN="${CLOUDFLARE_API_TOKEN:-}"
# Shared with backend — injected into proxied /api/ and /socket.io/ as X-API-Key
API_KEY="${API_KEY:-}"
SSL_DIR="/etc/nginx/ssl"
LE_DIR="/etc/letsencrypt"
CF_CREDS="${LE_DIR}/cloudflare.ini"
NGINX_TEMPLATE="${NGINX_TEMPLATE:-/etc/nginx/nginx.conf.template}"
NGINX_CONF="${NGINX_CONF:-/etc/nginx/nginx.conf}"

mkdir -p "${SSL_DIR}" "${LE_DIR}"

log() {
  echo "[nginx-entrypoint] $*"
}

render_nginx_conf() {
  # Compose mounts nginx.conf as a template; substitute API_KEY for backend auth headers.
  local src="${NGINX_TEMPLATE}"
  if [[ ! -f "${src}" ]]; then
    if [[ -f /etc/nginx/nginx.conf ]]; then
      src=/etc/nginx/nginx.conf
    else
      log "ERROR: nginx config template not found at ${NGINX_TEMPLATE}"
      exit 1
    fi
  fi

  export API_KEY
  if command -v envsubst >/dev/null 2>&1; then
    envsubst '${API_KEY}' < "${src}" > "${NGINX_CONF}.tmp"
    mv "${NGINX_CONF}.tmp" "${NGINX_CONF}"
  else
    # Fallback if gettext is missing
    sed "s|\${API_KEY}|${API_KEY}|g" "${src}" > "${NGINX_CONF}.tmp"
    mv "${NGINX_CONF}.tmp" "${NGINX_CONF}"
  fi

  if [[ -n "${API_KEY}" ]]; then
    log "Rendered nginx.conf with X-API-Key injection for /api/ and /socket.io/"
  else
    log "API_KEY unset — proxying without a backend API key (auth disabled on backend if also unset)"
  fi
}

trim() {
  local s="$1"
  s="${s#"${s%%[![:space:]]*}"}"
  s="${s%"${s##*[![:space:]]}"}"
  printf '%s' "${s}"
}

ensure_self_signed() {
  if [[ -f "${SSL_DIR}/cert.pem" && -f "${SSL_DIR}/key.pem" ]]; then
    return 0
  fi

  log "Generating temporary self-signed certificate for bootstrap HTTPS"
  openssl req -x509 -nodes -newkey rsa:2048 -days 1 \
    -keyout "${SSL_DIR}/key.pem" \
    -out "${SSL_DIR}/cert.pem" \
    -subj "/CN=${DOMAIN_NAME:-localhost}" >/dev/null 2>&1
}

link_letsencrypt_certs() {
  local domain="$1"
  local live="${LE_DIR}/live/${domain}"

  if [[ -f "${live}/fullchain.pem" && -f "${live}/privkey.pem" ]]; then
    rm -f "${SSL_DIR}/cert.pem" "${SSL_DIR}/key.pem"
    ln -sfn "${live}/fullchain.pem" "${SSL_DIR}/cert.pem"
    ln -sfn "${live}/privkey.pem" "${SSL_DIR}/key.pem"
    return 0
  fi
  return 1
}

write_cloudflare_credentials() {
  umask 077
  cat > "${CF_CREDS}" <<EOF
# Generated by nginx entrypoint — do not commit
dns_cloudflare_api_token = ${CLOUDFLARE_API_TOKEN}
EOF
  chmod 600 "${CF_CREDS}"
}

append_domain_flags() {
  # Appends -d flags to the named array passed by nameref
  local -n _out="$1"
  local extra d
  _out+=(-d "${DOMAIN_NAME}")
  if [[ -n "${CERTBOT_DOMAINS}" ]]; then
    IFS=',' read -ra extra <<< "${CERTBOT_DOMAINS}"
    for d in "${extra[@]}"; do
      d="$(trim "${d}")"
      [[ -n "${d}" ]] || continue
      _out+=(-d "${d}")
    done
  fi
}

obtain_certificate() {
  local email="$1"
  local -a cmd=(
    certbot certonly
    --dns-cloudflare
    --dns-cloudflare-credentials "${CF_CREDS}"
    --dns-cloudflare-propagation-seconds 30
    --email "${email}"
    --agree-tos
    --no-eff-email
    --non-interactive
    --keep-until-expiring
    --cert-name "${DOMAIN_NAME}"
  )

  if [[ "${CERTBOT_STAGING}" == "1" || "${CERTBOT_STAGING}" == "true" ]]; then
    cmd+=(--staging)
    log "Using Let's Encrypt staging environment"
  fi

  append_domain_flags cmd

  log "Requesting Let's Encrypt certificate via Cloudflare DNS-01 for ${DOMAIN_NAME}"
  "${cmd[@]}"
}

renew_loop() {
  while true; do
    sleep "${CERTBOT_RENEW_INTERVAL_SECONDS}"
    log "Running certbot renew"
    if certbot renew \
      --dns-cloudflare-credentials "${CF_CREDS}" \
      --quiet \
      --deploy-hook "nginx -s reload"; then
      if [[ -n "${DOMAIN_NAME}" ]] && link_letsencrypt_certs "${DOMAIN_NAME}"; then
        nginx -s reload || true
      fi
    else
      log "certbot renew reported an error (will retry on next interval)"
    fi
  done
}

certbot_enabled() {
  [[ -n "${DOMAIN_NAME}" && -n "${CERTBOT_EMAIL}" && -n "${CLOUDFLARE_API_TOKEN}" ]]
}

render_nginx_conf

# Prefer existing LE certs, then mounted/custom ssl, else bootstrap self-signed.
if [[ -n "${DOMAIN_NAME}" ]] && link_letsencrypt_certs "${DOMAIN_NAME}"; then
  log "Using existing Let's Encrypt certificate for ${DOMAIN_NAME}"
elif [[ -f "${SSL_DIR}/cert.pem" && -f "${SSL_DIR}/key.pem" ]]; then
  log "Using certificates already present in ${SSL_DIR}"
else
  ensure_self_signed
fi

if certbot_enabled; then
  write_cloudflare_credentials
  if ! link_letsencrypt_certs "${DOMAIN_NAME}"; then
    if obtain_certificate "${CERTBOT_EMAIL}"; then
      link_letsencrypt_certs "${DOMAIN_NAME}" || true
      log "Certificate installed; HTTPS ready for ${DOMAIN_NAME}"
    else
      log "Initial certificate request failed; continuing with current TLS material"
    fi
  fi
elif [[ -n "${DOMAIN_NAME}" || -n "${CERTBOT_EMAIL}" || -n "${CLOUDFLARE_API_TOKEN}" ]]; then
  log "Set DOMAIN_NAME, CERTBOT_EMAIL, and CLOUDFLARE_API_TOKEN to enable Let's Encrypt"
else
  log "Certbot env unset — serving without Let's Encrypt auto-issuance"
fi

# Run nginx in foreground as a sibling of the renew loop (do not exec away).
nginx -g 'daemon off;' &
nginx_pid=$!

cleanup() {
  kill "${nginx_pid}" 2>/dev/null || true
  wait "${nginx_pid}" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

if certbot_enabled; then
  renew_loop &
  log "Certbot auto-renewal enabled (every ${CERTBOT_RENEW_INTERVAL_SECONDS}s)"
fi

wait "${nginx_pid}"
trap - EXIT INT TERM
