#!/usr/bin/env node
/**
 * Generate a cryptographically secure API_KEY and autofill env files.
 *
 * Default targets (Docker / production shared secret):
 *   - .env
 *   - apps/backend/.env
 *
 * With --local (npm run dev without nginx):
 *   - also apps/frontend/.env → NEXT_PUBLIC_API_KEY
 *
 * Usage:
 *   node scripts/generate-api-key.mjs
 *   node scripts/generate-api-key.mjs --force
 *   node scripts/generate-api-key.mjs --local
 *   node scripts/generate-api-key.mjs --dry-run --print
 *   npm run generate:api-key
 */

import { randomBytes } from 'node:crypto';
import {
  existsSync,
  readFileSync,
  writeFileSync,
  copyFileSync,
  mkdirSync,
} from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const args = new Set(process.argv.slice(2));
const FORCE = args.has('--force') || args.has('-f');
const LOCAL = args.has('--local') || args.has('-l');
const DRY_RUN = args.has('--dry-run') || args.has('-n');
const PRINT = args.has('--print') || args.has('-p') || DRY_RUN;
const HELP = args.has('--help') || args.has('-h');

if (HELP) {
  console.log(`Generate and autofill DomainPeek API_KEY

Usage:
  node scripts/generate-api-key.mjs [options]
  npm run generate:api-key -- [options]

Options:
  --force, -f     Overwrite an existing non-empty API_KEY
  --local, -l     Also set NEXT_PUBLIC_API_KEY in apps/frontend/.env (local/dev without nginx)
  --dry-run, -n   Show what would change; do not write files
  --print, -p     Print the generated key to stdout
  --help, -h      Show this help

Creates each .env from its .env.example when missing.
`);
  process.exit(0);
}

/** URL-safe base64 without padding — avoids shell/envsubst special chars */
function generateApiKey(bytes = 32) {
  return randomBytes(bytes).toString('base64url');
}

function readEnvValue(content, key) {
  const re = new RegExp(`^${key}=(.*)$`, 'm');
  const match = content.match(re);
  if (!match) return undefined;
  return match[1].replace(/^["']|["']$/g, '').trim();
}

function upsertEnvKey(content, key, value) {
  const line = `${key}=${value}`;
  const re = new RegExp(`^#?\\s*${key}=.*$`, 'm');
  if (re.test(content)) {
    return content.replace(re, line);
  }
  const trimmed = content.replace(/\s*$/, '');
  return `${trimmed}\n\n# Generated by scripts/generate-api-key.mjs\n${line}\n`;
}

function ensureEnvFile(envPath, examplePath) {
  if (existsSync(envPath)) {
    return { created: false, content: readFileSync(envPath, 'utf8') };
  }
  if (existsSync(examplePath)) {
    if (!DRY_RUN) {
      mkdirSync(dirname(envPath), { recursive: true });
      copyFileSync(examplePath, envPath);
    }
    return {
      created: true,
      content: readFileSync(examplePath, 'utf8'),
    };
  }
  if (!DRY_RUN) {
    mkdirSync(dirname(envPath), { recursive: true });
    writeFileSync(envPath, `# Created by scripts/generate-api-key.mjs\n`, 'utf8');
  }
  return { created: true, content: '' };
}

function writeTarget({ label, envPath, examplePath, key, value }) {
  const { created, content } = ensureEnvFile(envPath, examplePath);
  const existing = readEnvValue(content, key);
  const hasValue = Boolean(existing);

  if (hasValue && !FORCE) {
    console.log(`⏭  ${label}: ${key} already set (use --force to rotate)`);
    return { skipped: true, key: existing };
  }

  const next = upsertEnvKey(content, key, value);
  if (!DRY_RUN) {
    writeFileSync(envPath, next, 'utf8');
  }

  const action = hasValue ? 'rotated' : created ? 'created+set' : 'set';
  console.log(`${DRY_RUN ? '🔍' : '✓'} ${label}: ${key} ${action}${DRY_RUN ? ' (dry-run)' : ''}`);
  return { skipped: false, key: value };
}

const apiKey = generateApiKey(32);

const targets = [
  {
    label: 'root',
    envPath: join(ROOT, '.env'),
    examplePath: join(ROOT, '.env.example'),
    key: 'API_KEY',
    value: apiKey,
  },
  {
    label: 'backend',
    envPath: join(ROOT, 'apps', 'backend', '.env'),
    examplePath: join(ROOT, 'apps', 'backend', '.env.example'),
    key: 'API_KEY',
    value: apiKey,
  },
];

if (LOCAL) {
  targets.push({
    label: 'frontend (local)',
    envPath: join(ROOT, 'apps', 'frontend', '.env'),
    examplePath: join(ROOT, 'apps', 'frontend', '.env.example'),
    key: 'NEXT_PUBLIC_API_KEY',
    value: apiKey,
  });
}

console.log(
  DRY_RUN
    ? 'Dry-run: generating API key (no files written)\n'
    : 'Generating API key and autofilling env files…\n'
);

let wroteAny = false;
for (const target of targets) {
  const result = writeTarget(target);
  if (!result.skipped) wroteAny = true;
}

if (PRINT || wroteAny) {
  console.log(`\nAPI_KEY=${apiKey}`);
}

if (!LOCAL) {
  console.log(
    '\nTip: for npm run dev without nginx, re-run with --local to also set NEXT_PUBLIC_API_KEY.'
  );
}

console.log(
  'With Docker nginx profile, root .env API_KEY is passed to backend + nginx (browser stays key-free).'
);
